### ISSUE TITLE
Añadir descripción del proyecto.

### ISSUE THREAD

**Issue by RodolfoFerro** [futurelabmx/dszoo#6]

**Comment by RodolfoFerro** [comment]
Definir estructura útil basada en:
- https://www.makeareadme.com

**Comment by PAGuardado** [comment]
@RodolfoFerro He hecho algunas modificaciones al README.md

**Comment by PAGuardado** [comment]
ya había un avance en el README.md... de todas maneras no quería dejar de hacer mi parte!

**Comment by PAGuardado** [comment]
https://github.com/futurelabmx/dszoo/pull/24
