### ISSUE TITLE
Familiarizarse con GitHub.

### ISSUE THREAD

**Issue by RodolfoFerro** [futurelabmx/dszoo#9]
Familiarizarse con el uso de Git desde línea de comandos y GitHub.

Añadir un aporte interesante para marcar esta tarea como leída.

**Comment by RodolfoFerro** [comment]
Recurso gráfico: https://learngitbranching.js.org

**Comment by RamiroFuentes** [comment]
El uso de entornos gráficos para el control de versiones en git vuelve muy sencillo este tipo de tareas para quienes no les gusta usar la linea de comandos. Un ejemplo puede ser GitKraken, uno de los mas usados entornos para control de versiones. https://www.gitkraken.com
